import inspect
from unittest.mock import MagicMock

import pytest

from ebonite import Ebonite
from ebonite.client.autogen import AUTOGEN_CLASSES, find_exposed_methods
from ebonite.client.expose import ExposedMethod
from ebonite.core.objects.core import EboniteObject
from ebonite.repository import ArtifactRepository, MetadataRepository
from tests.conftest import MockMixin


@pytest.mark.parametrize('base', AUTOGEN_CLASSES)
def test_all_exposed(base):
    assert find_exposed_methods(base) == []


object_exposed = [e for base in AUTOGEN_CLASSES
                  for e in find_exposed_methods(base, False) if issubclass(base, EboniteObject)]


@pytest.mark.parametrize('exposed', object_exposed, ids=[e.name for e in object_exposed])
def test_objects(exposed: ExposedMethod, mock_ebnt):
    method = getattr(mock_ebnt, exposed.name, None)
    args = [i for i, _ in enumerate(exposed.get_signature().args)]
    obj = type('obj', (), {exposed.original_name: MagicMock(name=exposed.original_name)})()
    method(obj, *args)
    getattr(obj, exposed.original_name).assert_called_with(*args)


meta_exposed = [e for e in find_exposed_methods(MetadataRepository, False)]


class MockMeta(MetadataRepository, MockMixin, proxy_mode=False):
    pass


class MockArt(ArtifactRepository, MockMixin, proxy_mode=False):
    pass


@pytest.fixture
def mock_ebnt():
    class MockEbonite(Ebonite):
        _bind = MagicMock(name='_bind')

        def __init__(self):
            super().__init__(MockMeta(), MockArt())

    return MockEbonite()


@pytest.mark.parametrize('exposed', meta_exposed, ids=[e.name for e in meta_exposed])
def test_metadata(exposed: ExposedMethod, mock_ebnt):
    method = getattr(mock_ebnt, exposed.name, None)
    args = [i for i, _ in enumerate(exposed.get_signature().args)]
    method(*args)
    mock_ebnt._bind.assert_called()
    getattr(mock_ebnt.meta_repo, exposed.original_name).assert_called_with(*args)


all_exposed = [e for base in AUTOGEN_CLASSES for e in find_exposed_methods(base, False)]


@pytest.mark.parametrize('exposed', all_exposed, ids=[e.name for e in all_exposed])
def test_exposed_code_equals(exposed: ExposedMethod):
    method = getattr(Ebonite, exposed.name, None)
    generated = exposed.generate_code()
    if method is None:
        return  # separate test for this
    actual = inspect.getsource(method)

    def striplines(s):
        return '\n'.join(line.strip() for line in s.split('\n'))

    msg = f'''inconsistent autogenerated code at
{method.__code__.co_filename}:{method.__code__.co_firstlineno}'''
    assert striplines(generated.strip()) == striplines(actual.strip()), msg
