version: "3.7"

services:
  metadata_store:
    image: postgres
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ebonite

  artifact_store:
    image: minio/minio:latest
    ports:
      - 8008:9000
    environment:
      MINIO_ACCESS_KEY: 'eboniteAccessKey'
      MINIO_SECRET_KEY: 'eboniteSecretKey'
    command:
      "server /data"
